name: Run Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install and Run test
      uses: abatilo/actions-poetry@v1.6.0
      with:
        python_version: 3.7.7
        poetry_version: 1.0.5
        args: install; poetry run pytest
